### ISSUE TITLE
CloudFoundryOperations interface does not looks enough

### ISSUE THREAD

**Issue by kiuby88** [kiuby88/brooklyn-cloudfoundry#17]
Currently, `CloudFoundryPaasLocation` uses a `CloudFoundryOperations` instance, which is provided by `CloudFoundryClientRegistry#getCloudFoundryClient(params)` method.

However, this interface does provided all the required to manage applications since `ApplicationV2` is required to scale an application (memory, disk and instances) as it is explained here [cf-java-client/issues#544](https://github.com/cloudfoundry/cf-java-client/issues/544). Then, `CloudFoundryPaasLocation` requieres manage the `Applicationv2` to scale an application.

**Comment by kiuby88** [comment]
We can apply different solutions to fix this issue. We only need the find the smartest. 

`DefaultCloudFoundryOperations` (which is provided currently by `CloudFoundryClientRegistryImpl`)  provides a method to get the ApplicationV2. However, this class can not be extended because, although it uses a Builder pattern, it defines a `private` constructor, which can not be reached. So, if this class can not be extended the `StubbedCloudFoundryPaasClientRegistry` can not useful for testing. **So, `DefaultCloudFoundryOperations` can not be extended**.

We can refactor `CloudFoundryClientRegistry`: 

```
package org.apache.brooklyn.cloudfoundry.location;

import org.apache.brooklyn.util.core.config.ConfigBag;
import org.cloudfoundry.operations.CloudFoundryOperations;

public interface CloudFoundryClientRegistry {

    CloudFoundryOperations getCloudFoundryOperations(ConfigBag conf, boolean allowReuse);
    CloudFoundryClient getCloudFoundryClient(ConfigBag conf, boolean allowReuse);
}
```

Then, the registry can be used to obtain an `client` or the superior layer, `CloudFoundyOperations`. However, it does not look the smartest solution.  

A different way. We can force to `CloudFoundryClientRegistry` to provide a `client` directly, instead of operations. Then, `CloudFoundryPaasLocation` should be in charge of creating a `CloudFoundryOperations` object when it will be necessary. But from my point of view this solution is worse that previous one.

Last suggestion. We can wrap `DefaultCloudFoundryOperations` under a new interface. But, I am not sure about that, because `CloudFoundryPaasLocation` would lose a lot of prominence. In this case, `CloudFoundryClientRegistry` provides a instance of this wrapper.

**Comment by andreaturli** [comment]
https://github.com/cloudfoundry/cf-java-client#cloudfoundryoperations-builder says explicitly `The CloudFoundryClient, DopplerClient, and UaaClients provide direct access to the raw REST APIs. This level of abstraction provides the most detailed and powerful access to the Cloud Foundry instance, but also requires users to perform quite a lot of orchestration on their own. Most users will instead want to work at the CloudFoundryOperations layer.` so if you need more control as you are a super user, then you probably want to use `CloudFoundryClient`

**Comment by kiuby88** [comment]
I am not sure if It is worth focusing on the `client`. Operations offer a good interesting management of the applications, and we would only need the `client` for the methods:  `setMemory`, `setDisk` and `setInstances`. The rest of `CloudFoundryPaasLocation` can continue using the operations (and it makes sense from my side). 

Since `DefaultCloudFoundryOperations` provides a method to get the client (`getClient`) we could force to registry to return `DefaultCloudFoundryOperations` instead of `CloudFoundryOperations` interface, and use the client in `set/memory/disk/instances`. 

However, we found here a testing problem, because `DefaultCloudFoundryOperations`  is a final class which uses a private constructor and an Builder. So, we can not mock anything there.

**Comment by kiuby88** [comment]
Would it look reasonable that Registry provides `getClient` and `getOperations`?

**Comment by andreaturli** [comment]
What's the issue in getting the raw client put of operations when needed?

**Comment by kiuby88** [comment]
The problem is that currently, the registry return `CloudFoundryOperation` interface which does not provide any operation to get the client. We could force registry to return `DefaultCloudFoundryOperations`, a `CloudFoundryOperation` impl which contains a `getClient` method. However, `DefaultCloudFoundryOperations`  is a final class so it can not be mocked and it can not be extended too (private constructor + builder pattern). So it looks very complicate to create a `StubbedRegistry` which provides a fake `DefaultCloudFoundryOperations`.

**Comment by andreaturli** [comment]
what if https://github.com/kiuby88/brooklyn-cloudfoundry/blob/master/src/test/java/org/apache/brooklyn/cloudfoundry/location/FakeCloudFoundryClient.java implements `CloudFoundryOperations` + `getClient` as the `DefaultCloudFoundryOperations` ?

**Comment by kiuby88** [comment]
I thought about that, but there is not any interface which defines `getClient()`. There is only exists an abstract class, `_DefaultCloudFoundryOperations`, which uses a package modifier, https://github.com/cloudfoundry/cf-java-client/blob/master/cloudfoundry-operations/src/main/java/org/cloudfoundry/operations/_DefaultCloudFoundryOperations.java#L143-143

So, if we want to return `_DefaultCloudFoudnryOperation` we need to move the registry and the entities to  the package `org.cloudfoundry.operations`, and it does not look a good idea.

Thanks for your help here :)

**Comment by kiuby88** [comment]
I think we have different options:
1. Forcing registry to return the client instead of operations (does not like a good option)
2. Mocking the client and the rest of components in order to create the Operations, (it could be a error prone task if the any is modified in the client interface)
3. Using a mock framework which allows final classes to be mocked instead of mockito, such as PowerMock (it is very easy to integrate, but I am not sure if it is a good idea).
4. Modifying the Registry interface to provides different methods to get the client or the operations (It could be confusse for registry users).
5. Wrap the Operations and the client using a different (that ideas was avoided some weeks ago, because `CloudFoundryLocation` loses a lot of prominence.
6. Using `_DefaultCloudFoundryOperations` (this implies to move the code to org.cloudfoundry.operations package. I'd rather not. ) 

The 4 looks the least-bad option for me.

**Comment by kiuby88** [comment]
Ok, let's go to apply the 4 choice here

**Comment by kiuby88** [comment]
This Issue is solved in #16

**Comment by kiuby88** [comment]
I found a better solution. I can use the scale operation of `Applications` interface which can be mocked. #16 contains the new solution.

**Comment by kiuby88** [comment]
I have just updated the issue, [cf-java-client/issues/554](https://github.com/cloudfoundry/cf-java-client/issues/544#issuecomment-239040340) 💯
