### ISSUE TITLE
Potential refactoring: transform CloudFoundryPaasClient into a Supplier

### ISSUE THREAD

**Issue by andreaturli** [kiuby88/brooklyn-cloudfoundry#8]
Consider the following refactorings:

1.`CloudFoundryPaasClient` could easily become `CloudFoundryClientSupplier implements Supplier<CloudFoundryClient>` and you can move the additional methods like `CloudFoundryPaasClient.deploy` to the `PaasLocation` interface that will be implemented by classes like `CloudFoundryPaasLocation. This will simplify the structure and remove some duplications

**Comment by kiuby88** [comment]
I think this issue is already resolved
